aws-cloudformation-stackset/.rpdk-config
aws-cloudformation-stackset/pom.xml

Bumping to rpdk v2

---

aws-cloudformation-resourcedefaultversion/pom.xml
aws-cloudformation-resourcedefaultversion/src/test/java/software/amazon/cloudformation/resourcedefaultversion/TranslatorTest.java
aws-cloudformation-resourceversion/pom.xml
aws-cloudformation-resourceversion/src/test/java/software/amazon/cloudformation/resourceversion/TranslatorTest.java
aws-cloudformation-stackset/pom.xml

*Issue #, if available:* N/A
* updated Mockito 2.28.2
* updated TranslatorTest to be less specific on exception message due to variance in Lombok outputs

Updated dependencies and tests

---

aws-cloudformation-resourcedefaultversion/README.md
aws-cloudformation-resourcedefaultversion/src/test/java/software/amazon/cloudformation/resourcedefaultversion/CreateHandlerTest.java
aws-cloudformation-resourcedefaultversion/src/test/java/software/amazon/cloudformation/resourcedefaultversion/ReadHandlerTest.java
aws-cloudformation-resourcedefaultversion/src/test/java/software/amazon/cloudformation/resourcedefaultversion/UpdateHandlerTest.java
aws-cloudformation-resourceversion/README.md
aws-cloudformation-resourceversion/src/test/java/software/amazon/cloudformation/resourceversion/CreateHandlerTest.java

Changed the README file - updated Arn to TypeVersionArn in the DefaultVersion. Arn is the main Arn of the resource and TypeVersionArn refers to the specific Arn of the ResourceVersion. Hence, renaming it.
Updated: Removed incorrect assert statements in Unit tests(To check exception messages).

Changed the README file - updated Arn to TypeVersionArn in the DefaultVersion

---

aws-cloudformation-stackset/aws-cloudformation-stackset.json

* Loosen up tags regex for StackSet resource

Loosen up tags regex for StackSet resource

---

aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/translator/RequestTranslator.java

* UpdateStackSet honors operation preferences

UpdateStackSet honors operation preferences

---

aws-cloudformation-resourceversion/src/main/java/software/amazon/cloudformation/resourceversion/DeleteHandler.java
aws-cloudformation-resourceversion/src/main/java/software/amazon/cloudformation/resourceversion/ReadHandler.java

Add loggers in the Read and Delete handlers for better tracking. 

Add loggers in the Read and Delete handlers for better tracking

---

aws-cloudformation-stackset/aws-cloudformation-stackset.json
aws-cloudformation-stackset/pom.xml
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/translator/PropertyTranslator.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/translator/PropertyTranslatorTest.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/util/TestUtils.java

Add region concurrency support for StackSet resource

---

aws-cloudformation-moduledefaultversion/pom.xml
aws-cloudformation-moduledefaultversion/src/main/java/software/amazon/cloudformation/moduledefaultversion/CreateHandler.java
aws-cloudformation-moduleversion/pom.xml
aws-cloudformation-resourcedefaultversion/pom.xml
aws-cloudformation-resourceversion/pom.xml
aws-cloudformation-stackset/pom.xml
aws-cloudformation-typedefaultversion/pom.xml
aws-cloudformation-typeversion/pom.xml
checkstyle.xml

We can expand on the checkstyle rules. Starting off with enforcing the check for unused imports which should be the least contentious.

Add basic checkstyle rule

---

aws-cloudformation-stackset/aws-cloudformation-stackset.json
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/BaseHandlerStd.java
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/DeleteHandler.java
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/ListHandler.java
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/ReadHandler.java
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/translator/RequestTranslator.java
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/util/ResourceModelBuilder.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/CreateHandlerTest.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/DeleteHandlerTest.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/ListHandlerTest.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/ReadHandlerTest.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/UpdateHandlerTest.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/translator/PropertyTranslatorTest.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/util/TestUtils.java

Adds the callAs parameter to the StackSet resource, enabling use of delegated administration

Add callAs parameter to StackSet Resource

---

aws-cloudformation-moduledefaultversion/aws-cloudformation-moduledefaultversion.json
aws-cloudformation-moduledefaultversion/resource-role.yaml
aws-cloudformation-moduledefaultversion/src/main/java/software/amazon/cloudformation/moduledefaultversion/ListHandler.java
aws-cloudformation-moduledefaultversion/src/main/java/software/amazon/cloudformation/moduledefaultversion/Translator.java
aws-cloudformation-moduledefaultversion/src/test/java/software/amazon/cloudformation/moduledefaultversion/ListHandlerTest.java

Implement the ListHandler to ensure ModuleDefaultVersion will be compatible with future features which rely on correct implementation of all handlers

[ModuleDefaultVersion] Implement ListHandler

---

aws-cloudformation-moduleversion/pom.xml

- Upgrade dependencies for AWS::CloudFormation::ModuleVersion to make sure it passes contract tests.
*Test*
Use SAM and cfn-cli locally
```
collected 13 items / 4 deselected / 9 selected
handler_create.py::contract_create_delete PASSED                                                                                                                                                                                       [ 11%]
handler_create.py::contract_create_duplicate SKIPPED (No writable identifiers. Skipping test.)                                                                                                                                         [ 22%]
handler_create.py::contract_create_read_success PASSED …
```

Upgrade package dependencies

---

aws-cloudformation-moduleversion/overrides.json

Use dependency stack export instead of hardcode input data

---

aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/BaseHandlerStd.java
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/DeleteHandler.java
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/ListHandler.java
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/ReadHandler.java
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/UpdateHandler.java

StackSet - Remove DSS Call from Call Graph
* Manual Testing

StackSet - Remove DSS Call from Call Graph

---

aws-cloudformation-stackset/aws-cloudformation-stackset.json
aws-cloudformation-stackset/pom.xml
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/UpdateHandler.java
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/translator/PropertyTranslator.java
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/translator/RequestTranslator.java
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/util/Comparator.java
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/util/ResourceModelBuilder.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/UpdateHandlerTest.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/translator/PropertyTranslatorTest.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/util/ComparatorTest.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/util/TestUtils.java

StackSets - Add Support On ManagedExecution with commit histories

StackSets - ManagedExecution 

---

aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/BaseHandlerStd.java
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/CreateHandler.java
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/DeleteHandler.java
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/UpdateHandler.java
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/translator/RequestTranslator.java

- Add logging for service requests for better debugging
- Attach roles while updating `ManagedExecution` as it might fail `passRole` check

StackSets - Add logging for service requests and add roles for update ME

---

.github/workflows/java-ci-with-maven.yml
aws-cloudformation-moduledefaultversion/pom.xml
aws-cloudformation-moduleversion/pom.xml
aws-cloudformation-resourcedefaultversion/pom.xml
aws-cloudformation-resourceversion/pom.xml
aws-cloudformation-stackset/aws-cloudformation-stackset.json
aws-cloudformation-stackset/pom.xml
aws-cloudformation-stackset/resource-role.yaml

StackSets - Increase timeout to 2160 and bump versions in pom

---

aws-cloudformation-stackset/aws-cloudformation-stackset.json
aws-cloudformation-stackset/docs/README.md
aws-cloudformation-stackset/docs/deploymenttargets.md
aws-cloudformation-stackset/pom.xml
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/BaseHandlerStd.java
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/translator/PropertyTranslator.java
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/util/AltResourceModelAnalyzer.java
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/util/AltStackInstancesCalculator.java
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/util/Comparator.java
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/util/Validator.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/CreateHandlerTest.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/DeleteHandlerTest.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/UpdateHandlerTest.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/translator/PropertyTranslatorTest.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/util/AltResourceModelAnalyzerTest.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/util/AltStackInstancesCalculatorTest.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/util/AltTestUtils.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/util/ComparatorTest.java

*Description of changes:* Account-level targeting resource provider

Account-level targeting resource provider

---

aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/BaseHandlerStd.java

*Description of changes: adding status reason in operation failure message

Add status reason in operation failure message

---

aws-cloudformation-stackset/aws-cloudformation-stackset.json
aws-cloudformation-stackset/resource-role.yaml
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/BaseHandlerStd.java
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/translator/RequestTranslator.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/CreateHandlerTest.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/util/TestUtils.java

Update operation failure message to be more detailed

---

aws-cloudformation-stackset/docs/README.md
aws-cloudformation-stackset/docs/tag.md
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/BaseHandlerStd.java
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/util/Validator.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/CreateHandlerTest.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/UpdateHandlerTest.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/util/TestUtils.java

Stack Sets supports nested stacks for self managed stack sets.  in order to support feature parity, the resource handler should be updated to match that behavior. 

add support for nested stacks in self managed stack sets

---

aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/translator/RequestTranslator.java

Add callAs parameter to updateManagedExecutionRequest

---

aws-cloudformation-moduleversion/contract-tests-artifacts/pre-script/fragments/sample.json
aws-cloudformation-moduleversion/contract-tests-artifacts/pre-script/prescript.yml
aws-cloudformation-moduleversion/contract-tests-artifacts/pre-script/schema.json
aws-cloudformation-moduleversion/pom.xml
aws-cloudformation-moduleversion/src/test/java/software/amazon/cloudformation/moduleversion/ReadHandlerTest.java

* Make AWS-SDK versions consistent with [those used in cfn-cli](https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/blob/master/pom.xml#L40)
* Some more package upgrades
*  Ensure temporary Contract Test Bucket is not publicly accessible

[ModuleVersion] Upgrade several libraries

---

aws-cloudformation-stackset/aws-cloudformation-stackset.json

These permissions are required to use the StackSets resource

[StackSets] Add missing required permissions to stack set handlers

---

aws-cloudformation-stackset/docs/deploymenttargets.md
aws-cloudformation-stackset/resource-role.yaml
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/util/AltResourceModelAnalyzer.java
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/util/AltStackInstancesCalculator.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/util/AltResourceModelAnalyzerTest.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/util/AltStackInstancesCalculatorTest.java

- Changed the check method for ALT analyzer 
- Fixed AltStackInstances check for creation
- Corrected the unit tests to suit for the current ALT analyzer and calculate code

Fix AltStackInstances check for create

---

aws-cloudformation-stackset/aws-cloudformation-stackset.json

cr: https://code.amazon.com/reviews/CR-166548407
https://issues.amazon.com/issues/CFN-105719
Add tagging information to stackset resource schema

Add tagging information to stackset resource schema
