aws-cloudformation-resourcedefaultversion/src/main/java/software/amazon/cloudformation/resourcedefaultversion/CreateHandler.java
aws-cloudformation-resourcedefaultversion/src/test/java/software/amazon/cloudformation/resourcedefaultversion/CreateHandlerTest.java

*Issue #, if available:* N/A
*Description of changes:* Missed this commit on #4 before merging. Fixes the handling of default version checks for `AWS::CloudFormation::ResourceDefaultVersion`.

Fixed defect in default version check

---

aws-cloudformation-resourcedefaultversion/pom.xml
aws-cloudformation-resourcedefaultversion/src/test/java/software/amazon/cloudformation/resourcedefaultversion/CreateHandlerTest.java
aws-cloudformation-resourcedefaultversion/src/test/java/software/amazon/cloudformation/resourcedefaultversion/ReadHandlerTest.java
aws-cloudformation-resourcedefaultversion/src/test/java/software/amazon/cloudformation/resourcedefaultversion/UpdateHandlerTest.java
aws-cloudformation-resourceversion/aws-cloudformation-resourceversion.json
aws-cloudformation-resourceversion/pom.xml
aws-cloudformation-resourceversion/resource-role.yaml
aws-cloudformation-resourceversion/src/test/java/software/amazon/cloudformation/resourceversion/CreateHandlerTest.java
aws-cloudformation-stackset/pom.xml

*Issue #, if available:* N/A
*Description of changes:* Recent changes to the Registry Service auth model require the caller to have S3 permissions for object retrieval over the `SchemaHandlerPackage`

Adds required S3 permissions to the schema.

---

aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/BaseHandlerStd.java
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/UpdateHandler.java

* Configure timeout for UpdateStackSets to fix the bug that when UpdateStackSet operation takes long time causing timeout exception
* Add more logs for debugging

Configure timeout for UpdateStackSets and Add Loggings

---

aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/Configuration.java
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/CreateHandler.java
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/UpdateHandler.java
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/translator/PropertyTranslator.java
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/translator/RequestTranslator.java
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/util/ClientBuilder.java
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/util/Comparator.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/CreateHandlerTest.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/UpdateHandlerTest.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/util/ClientBuilderTest.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/util/ComparatorTest.java

* StackSet handlers take stack tags
* Add retry strategy for CloudFormation client in StackSet
*Testing*
* Manual create/update stack with stack tags.

StackSets Takes StackTags and Retry Strategy When Throttling

---

aws-cloudformation-moduleversion/aws-cloudformation-moduleversion.json
aws-cloudformation-moduleversion/docs/README.md
aws-cloudformation-moduleversion/overrides.json
aws-cloudformation-moduleversion/src/main/java/software/amazon/cloudformation/moduleversion/CreateHandler.java

I had originally left `ModuleVersion`'s `ModulePackage` field out of the "required" fields in the schema because it was causing issues with contract tests (i.e. contract tests would fail when attempting a delete operation because the module package field was required, but cannot be read in `DescribeType` requests and supplied to the delete handler [#318](https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/issues/318)). I had temporarily implemented manual validation in the `ModuleVersion` create handler to check for `ModulePackage` to compensate.
After building, running the unit tests, and testing these changes manually in my account through a number of create-, update-, and delete-stack operations, I am confident setting `ModulePackage` as "required" is safe, despite …

Setting ModuleVersion's ModulePackage field to "required"

---

aws-cloudformation-stackset/aws-cloudformation-stackset.json

https://json-schema.org/understanding-json-schema/reference/combining.html
https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-cloudformation/issues/17
```bash
$ grep -l -E -i '(oneOf|anyOf|allOf)' * # other combined resource schemas to look into from https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-type-schemas.html
aws-applicationinsights-application.json
a̶w̶s̶-̶c̶l̶o̶u̶d̶f̶o̶r̶m̶a̶t̶i̶o̶n̶-̶m̶o̶d̶u̶l̶e̶d̶e̶f̶a̶u̶l̶t̶v̶e̶r̶s̶i̶o̶n̶.̶j̶s̶o̶n̶
a̶w̶s̶-̶c̶l̶o̶u̶d̶f̶o̶r̶m̶a̶t̶i̶o̶n̶-̶s̶t̶a̶c̶k̶s̶e̶t̶.̶j̶s̶o̶n̶
aws-cloudwatch-metricstream.json
a̶w̶s̶-̶d̶a̶t̶a̶b̶r̶e̶w̶-̶d̶a̶t̶a̶s̶e̶t̶.̶j̶s̶o̶n̶
a̶w̶s̶-̶d̶a̶t̶a̶b̶r̶e̶w̶-̶r̶e̶c̶i̶p̶e̶.̶j̶s̶o̶n̶
a̶w̶s̶-̶g̶a̶m̶e̶l̶i̶f̶t̶-̶a̶l̶i̶a̶s̶.̶j̶s̶o̶n̶
a̶w̶s̶-̶k̶e̶n̶d̶r̶a̶-̶d̶a̶t̶a̶s̶o̶u̶r̶c̶e̶.̶j̶s̶o̶n̶ …
```

moving required AWS::CloudFormation::StackSet properties out of oneOf

---

aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/util/Comparator.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/util/ComparatorTest.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/util/TestUtils.java

*Issue #38*
* Fix StackSet Update - Update will be not triggered if only update Parameters/AutoDeployment
- Only update `AutoDeployment` 
- Only update `Parameters`
```
Resources:
TestStackSet:
Type: AWS::CloudFormation::StackSet
Properties:
StackSetName: StackSet-UpdateTest
Description: Description
PermissionModel: SERVICE_MANAGED
AutoDeployment:
Enabled: true
RetainStacksOnAccountRemoval: true
Parameters:
- ParameterKey: Number
ParameterValue: 150
TemplateBody: |
Parameters:
Number:
Type: "String"
Resources:
WaitCondition: 
Type: AWS::CloudFormation::WaitCondition
Properties: 
Timeout: !Ref Number
Outputs:
StackSetId:
Value: !Ref TestStackSet
```

Fix StackSet Update - Only update Parameters/AutoDeployment

---

aws-cloudformation-resourceversion/aws-cloudformation-resourceversion.json

Having the properties -ExecutionRoleArn, LoggingConfig, SchemaHandlerPackage and TypeName as createOnly would make it clear that no properties are updatable for this resource. Also makes it clear that they cause a replacement.
Reference customer PR: https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-cloudformation/pull/24

Add createOnlyProperties to the ResourceVersion resource

---

.github/workflows/java-ci-with-maven.yml

Issue #, if available:
Description of changes: Migrates the Travis continuous integration jobs to GitHub actions. Similar to: aws-cloudformation/aws-cloudformation-resource-providers-logs#54
This is required because AWS-CloudFormation's Travis CI subscription has expired. So, Travis CI builds after 19-03-2021 in this repo are not finishing.

Migrate repo from TravisCI to GitHub actions

---

.github/workflows/java-ci-with-maven.yml
aws-cloudformation-moduledefaultversion/src/main/java/software/amazon/cloudformation/moduledefaultversion/CreateHandler.java
aws-cloudformation-moduledefaultversion/src/test/java/software/amazon/cloudformation/moduledefaultversion/CreateHandlerTest.java

#49 
I had looked at checking if the default version is the _same_ as the one that we're trying to set. But it seems that that the API doesn't throw an error in that case. The only issue I can see is that this could allow a different stack to manage the same default version resource.
[ResourceDefaultVersion ](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-cloudformation/blob/master/aws-cloudformation-resourcedefaultversion/src/main/java/software/amazon/cloudformation/resourcedefaultversion/CreateHandler.java)does not have this check.

do not check if module default version exists

---

aws-cloudformation-stackset/aws-cloudformation-stackset.json

Customers report that `:` is disallowed in StackSet resource while is allowed in Stack resource and StackSets service.
Update TagKey pattern to allow `:`
*Testing*:
* RegEx testing
* Manual build

StackSets - Tag Key allows colon

---

aws-cloudformation-moduleversion/src/main/java/software/amazon/cloudformation/moduleversion/Translator.java
aws-cloudformation-moduleversion/src/test/java/software/amazon/cloudformation/moduleversion/TranslatorTest.java

Including a clientRequestToken when calling register-type. This can help when investigating issues on the registry side

Include ClientRequestToken in call to RegisterType

---

aws-cloudformation-moduledefaultversion/.rpdk-config
aws-cloudformation-moduleversion/src/main/java/software/amazon/cloudformation/moduleversion/CallbackContext.java
aws-cloudformation-moduleversion/src/main/java/software/amazon/cloudformation/moduleversion/CreateHandler.java
aws-cloudformation-moduleversion/src/main/java/software/amazon/cloudformation/moduleversion/Translator.java
aws-cloudformation-moduleversion/src/test/java/software/amazon/cloudformation/moduleversion/TranslatorTest.java

The CreateHandler is being called multiple times by the CloudFormation framework (documented for example [here](https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-walkthrough.html)), so we have to make sure it's idempotent. To do that we ensure the same clientRequestToken is sent along with the register type call. The current bug is triggered because the random clientRequestTokens cause the hash of the RegisterTypeRequest to be different between CreateHandler invokation which causes CFN to resend the request (see [hashing of the request here](https://github.com/aws-cloudformation/cloudformation-cli-java-plugin/blob/master/src/main/java/software/amazon/cloudformation/proxy/AmazonWebServicesClientProxy.java#L265))
By submitting this pull request, I confirm that …

SkyTrain-NS-259 Bugfix: Ensure same client request token is used when register-type is resent

---

aws-cloudformation-moduledefaultversion/src/main/java/software/amazon/cloudformation/moduledefaultversion/ClientBuilder.java
aws-cloudformation-moduleversion/src/main/java/software/amazon/cloudformation/moduleversion/ClientBuilder.java
aws-cloudformation-resourcedefaultversion/src/main/java/software/amazon/cloudformation/resourcedefaultversion/ClientBuilder.java
aws-cloudformation-resourceversion/src/main/java/software/amazon/cloudformation/resourceversion/ClientBuilder.java
aws-cloudformation-typedefaultversion/src/main/java/software/amazon/cloudformation/typedefaultversion/ClientBuilder.java
aws-cloudformation-typeversion/src/main/java/software/amazon/cloudformation/typeversion/ClientBuilder.java

Update AWS cloudformation client configurations to use new STANDARD mode.
Note:  I did not make changes to stackset retry mode as current retry mode already overridden so not changing it.

Adopting the AWS Java SDK's Standard Retry Mode

---

.github/workflows/java-ci-with-maven.yml
aws-cloudformation-stackset/pom.xml
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/ListHandler.java
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/translator/RequestTranslator.java

Preivously, we list all stacksets including `Deleted` Stacksets, that causes an unnecessary latency issue to users who have a lot of StackSets deleted before.
Optimizing the List handler to call `ListStackSets` with `ACTIVE` status flag

StackSets - ListStackSetsRequest with ACTIVE status

---

aws-cloudformation-hooktypeconfig/src/test/java/software/amazon/cloudformation/hooktypeconfig/TranslatorTest.java

Newer version of Lombok changed the word `@NonNull` in error message to `non-null`, which results in unit tests to fail. 

Fix inconsistent expected error messages

---

aws-cloudformation-stackset/aws-cloudformation-stackset.json

*Description of changes:Allow StackSets to use template URL up to 5120 bytes long, consistent with API.

StackSets - Allow template URL to be up to 5120 bytes long

---

aws-cloudformation-moduleversion/aws-cloudformation-moduleversion.json

The ModuleVersion resource is currently not adhering to the [Resource type handler contract](https://docs.aws.amazon.com/cloudformation-cli/latest/userguide/resource-type-test-contract.html) specifically the rule that says that all readOnlyProperties must be returned in a read request. Theoretically, it would be a backwards-incompatible change to remove a property from readOnlyProperties, but since we have never returned this value in read requests in practice, this change won't break any existing customers.

[ModuleVersion] Remove DocumentationUrl from readOnlyProperties

---

aws-cloudformation-moduleversion/aws-cloudformation-moduleversion.json
aws-cloudformation-moduleversion/src/main/java/software/amazon/cloudformation/moduleversion/Translator.java

I made a mistake in my last PR. I can't remove DocumentationUrl from the readOnlyProperties, because that would enable users to specify it in the template which is not how the attribute is intended to be used. The contract tests are complaining that we're not always returning the documentationUrl. Removing it would be backwards-incompatible, so to adhere to the resource type contract we'll return an empty string when the module doesn't have a documentationUrl.

[ModuleVersion] Return empty string instead of null for DocumentationUrl

---

aws-cloudformation-moduleversion/aws-cloudformation-moduleversion.json

The ListHandler of the ModuleVersion resource does not behave as expected. It always returns an empty response because the paging logic is not implemented properly. Fixing it is no trivial, because we need to iterate over an unknown number of lists (the list of modules and for each module the list of versions), each of which has an iteration token. So, we should disable it to reduce confusion for customers. It's better to return a clear message saying the list handler is not supported than returning an incorrect response. We'll work on fixing the handler in the meantime.

Disable ModuleVersion ListHandler

---

aws-cloudformation-moduledefaultversion/pom.xml
aws-cloudformation-moduledefaultversion/src/main/java/software/amazon/cloudformation/moduledefaultversion/Translator.java
aws-cloudformation-moduledefaultversion/src/test/java/software/amazon/cloudformation/moduledefaultversion/ListHandlerTest.java

The contract tests expect that the ListHandler returns the default module versions, not the module itself.
Currently, when we invoke the ListHandler we get the Module arns like this:
```bash
aws cloudcontrol list-resources --type-name AWS::CloudFormation::ModuleDefaultVersion --region us-west-2
```
```json
{
"ResourceDescriptions": [
{
"Identifier": "arn:aws:cloudformation:us-west-2:123:type/module/Malik-mm-mm-MODULE",
"Properties": "{\"ModuleName\":\"Malik::mm::mm::MODULE\",\"Arn\":\"arn:aws:cloudformation:us-west-2:123:type/module/Malik-mm-mm-MODULE\"}"
}
],
"TypeName": "AWS::CloudFormation::ModuleDefaultVersion"
}
```
But, the expected output according to the resource contract is like this:
```json
{
"ResourceDescriptions": [
{
"Identifier": …
```

Make ModuleDefaultVersion ListHandler conform to contract tests

---

aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/util/AltResourceModelAnalyzer.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/util/AltResourceModelAnalyzerTest.java

- Adding changes to handle region order for ALT operations. Currently, we don't batch operations for ALT, as a result ALT operations don't follow region order. Batching operations will be the long term solution for this. I have created this solution as a short term fix
- Changed Hashmap to LinkedHashmap to maintain region order, same with HashSet(Changed it to LinkedHashSet to maintain the order of Stack Instances)
- The average time complexity for LinkedHashmap/HashSet v Hashmap/HashSet and  for Insert, Delete, Search is the same -> O(1)
- The worst time complexity for LinkedHashmap/HashSet v Hashmap/HashSet for Insert, Delete, Search is the same -> O(n)
- Manually tested the solution in my dev account
By submitting this pull request, I …

Handle RegionOrder Preference for ALT

---

aws-cloudformation-stackset/aws-cloudformation-stackset.json
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/CreateHandler.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/CreateHandlerTest.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/util/TestUtils.java

- Add stack set name as an additional identifier, as it can be used along with stack set id in all APIs
- Return AlreadyExists exception for duplicate resources, required as part of the CREATE handler contract

[StackSets] Add stack set name as an additional identifier; return AlreadyExists exception for duplicate resources

---

aws-cloudformation-hookdefaultversion/pom.xml
aws-cloudformation-hooktypeconfig/pom.xml
aws-cloudformation-hookversion/pom.xml
aws-cloudformation-stack/pom.xml
aws-cloudformation-stackset/aws-cloudformation-stackset.json
aws-cloudformation-stackset/docs/operationpreferences.md
aws-cloudformation-stackset/pom.xml
aws-cloudformation-stackset/src/main/java/software/amazon/cloudformation/stackset/translator/PropertyTranslator.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/translator/PropertyTranslatorTest.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/util/AltResourceModelAnalyzerTest.java
aws-cloudformation-stackset/src/test/java/software/amazon/cloudformation/stackset/util/TestUtils.java

*Description of changes:* This PR adds the ConcurrencyMode parameter to the AWS::CloudFormation::StackSet resource.

Add ConcurrencyMode Support for StackSet Resource
